# Generated by Django 5.0.3 on 2024-04-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PortCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ship')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('notify_party', models.CharField(max_length=100)),
                ('description_of_cargo', models.TextField()),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('master', models.CharField(max_length=100)),
                ('port_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portcall')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shipowner'),
        ),
    ]
